{% set name = "chealpix" %}
{% set version = "3.31" %}
{% set date = "2016Aug26" %}
{% set sha256 = "ddf437442b6d5ae7d75c9afaafc4ec43921f903c976e25db3c5ed5185a181542" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}.0"

source:
  url: "https://sourceforge.net/projects/healpix/files/Healpix_{{ version.split('.')[:2] | join('.') }}/Healpix_{{ version }}_{{ date }}.tar.gz"
  sha256: "{{ sha256 }}"

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  run_exports:
    - {{ pin_subpackage("chealpix", max_pin="x.x") }}
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - automake
    - {{ compiler('c') }}
    - libtool
    - make
    - pkg-config
    - sed
  host:
    - cfitsio
  run:
    - cfitsio

test:
  requires:
    - pkg-config  # [not win]
  commands:
    - test -f ${PREFIX}/include/chealpix.h  # [not win]
    - test -f ${PREFIX}/lib/libchealpix${SHLIB_EXT}  # [not win]
    - test $(pkg-config --modversion "${PKG_NAME}") == "${PKG_VERSION}"  # [not win]

about:
  home: "https://sourceforge.net/projects/healpix/"
  doc_url: "http://healpix.sf.net/documentation.php"
  dev_url: "https://sourceforge.net/projects/healpix/"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "Software for pixelization, hierarchical indexation, synthesis, analysis, and visualization of data on the sphere."
  description: |
    HEALPix is a Hierarchical, Equal Area, and iso-Latitude Pixelation of
    the sphere designed to support efficiently (1) local operations on the
    pixel set, (2) a hierarchical tree structure for multi-resolution
    applications, and (3) the global Fast Spherical Harmonic transform.
    HEALPix based mathematical software meets the challenges presented 
    by high resolution and large volume data sets, such as the WMAP and
    Planck CMB mission products.

extra:
  recipe-maintainers:
    - duncanmmacleod
