appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pthrCii4Ybza0TEavazlpjDsEYGArfq3WSZlSJv+k8DRWvF5O9PZabYvAU0OWbB+zN3xgOpyZZshdUFz6UBudMqZR15qAwe2zDcpbMKbqhGjijQihmOyDO4SFRo7npPVn8ZxkbS1GeTuNF4j0eAFMasqoZ9YXQdocoEb7xVivFUTXk3HoFeIMYwKpjR6hd8RPju5GjUEXxvGCqiDa/03TPQWfHt+B/GoA1iTgZyIiDjxTTcbWLHopJQe53cvWGvQlyqBel0REZ1XlK7so8kZ1H7NBhnlJNUyDofM4iTj+UBIbPeRpAiyt3KL1nHbeVyyI0vDxFPl2NVjikKx8BtlXC7zugzmVOq6GImgEy3nNZ9Ekn7GhPIWPNbYn1SCCmaxo2RcWhd6JQqXyYKZAva0V4gp5+6RVe0xAFQpierEMLgRon0mYdCRd0u/EjWAEa5jwsT90biXGmlf1sNnVSRl5uVmWSb2ycZY5NRpBip/yPz2LGH3a6xKZSkgUl8EYxegP+7nutRjZYY+zIbH8IBiIvGUlqJAU3M+CI49c3q5iyzwRaa8GpWJdy8qELV3hhvKIiv/vl/6Kh1DHZlVWtQ/hY0aPAk3IBnlqcXYesPJJcYPufZgQJHYhYCWrsHIJ4+HGkig/YUuw7x4dOHNzslgInAQwWwOGqqTgBBuJJmb6jk=}
